### ISSUE TITLE
Support django-graphql-jwt==0.3.1? Maybe resolve issue with info.context.user (permission)

### ISSUE THREAD

**Issue by patrykKlimczak** [PedroBern/django-graphql-auth#44] opened 2020-05-23 07:58 UTC
I try to get id with other model than user (or extend user model)
I use 
```
@login_required
    def resolve_posts_partner(self, info):
        print(info.context.user.id, 'my user partner id')
        return Post.objects.order_by('-updated_at').filter(partner_id=info.context.user.id)
```
and I have
![image](https://user-images.githubusercontent.com/18028886/82725225-c11e9800-9cdb-11ea-897e-2eea91598326.png)

When i delete @login_required

I have 
![image](https://user-images.githubusercontent.com/18028886/82725239-deebfd00-9cdb-11ea-927a-2c26bc596423.png)

problem with info.context.user.id

Maybe who help me?

**Comment by ulgens** [comment] 2020-05-23 08:07
I tried to update this package last week and got lost in broken stuff. I can try again.

**Comment by patrykKlimczak** [comment] 2020-05-23 08:30
@ulgens 
problem with `info.context.user.id` will be resolve with upgrade jwt package?

**Comment by ulgens** [comment] 2020-05-23 08:33
I don't have that issue with current master django-graphql-auth and 0.3 version of jwt package. If `info.context.user.id`is `None`, it looks like authentication is failing. I'm not sure this is realated to the packages.

**Comment by patrykKlimczak** [comment] 2020-05-23 08:39
@ulgens 
I wrote my case with this issue https://github.com/PedroBern/django-graphql-auth/issues/37#issuecomment-633001357

**Comment by patrykKlimczak** [comment] 2020-05-23 08:44
@ulgens 
One load page with two query
![image](https://user-images.githubusercontent.com/18028886/82726094-2c6b6880-9ce2-11ea-89c9-8d78d034deb7.png)


Two different sessions with id :O when I check change log 0.3.1 JWT maybe :)

**Comment by PedroBern** [comment] 2020-05-25 12:09
Hi @patrykKlimczak can you update your issue to use the issue template? When you have opened your issue it was already available. We can need need reproducible steps to help.

**Comment by patrykKlimczak** [comment] 2020-05-25 14:50
@PedroBern 
Done 
https://github.com/PedroBern/django-graphql-auth/issues/46


You can probably close it

**Comment by PedroBern** [comment] 2020-05-25 14:55
Closing in favor of #46

**Closed by PedroBern** 2020-05-25 14:55 UTC
